# Guess Game using Python

import random
comp_guess = random.randint(1,100) 
chances = 0

print("This is a guessing game and you have to enter a number and if it matches with the number generated by computer")
user_guess = int(input("\nEnter any number between 1 to 100: "))
chances += 1

while (user_guess != comp_guess):
    if user_guess > comp_guess:
        print("Entered number is greater, try a smaller number instead! \n")
        user_guess = int(input("Enter again: "))
        chances += 1
        continue

    elif user_guess < comp_guess:
        print("Entered number is smaller, try a greater number instead! \n")
        user_guess = int(input("Enter again: "))
        chances += 1
        continue

score = 100 - chances  
print(f"\nCongratulations the number computer guessed was {comp_guess}")
print(f"\nYou guessed it right in the {chances} attempt")
print(f"\nYour score is {score}")