# Generated by Django 4.2.1 on 2023-07-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('when', models.DateField()),
                ('count', models.IntegerField()),
                ('contact', models.JSONField()),
                ('time', models.CharField(max_length=50)),
            ],
        ),
    ]
