# Generated by Django 4.2.1 on 2023-06-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(max_length=2, verbose_name='Level: '),
        ),
    ]
